name: CI/CD Pipeline

# This workflow will run when pushing to the main branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment (optional, depending on if you need to build the Node app)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies and run tests (optional, depending on your setup)
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: docker build . -t sivaprasadpv/nodeappdocker:latest

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push sivaprasadpv/nodeappdocker:latest
